<?php
require 'config.php';

// Admin Security Check
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin') {
    header("Location: index.php");
    exit();
}

$today = date('Y-m-d');
$stmt = $dbh->prepare("SELECT * FROM reservations WHERE reservation_date = ? AND status IN ('pending', 'ongoing') ORDER BY reservation_time ASC");
$stmt->execute([$today]);
$daily_list = $stmt->fetchAll(PDO::FETCH_ASSOC);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Daily Reservation Log - <?php echo $today; ?></title>
    <style>
        body { font-family: 'Inter', sans-serif; padding: 40px; color: #333; }
        .print-header { text-align: center; border-bottom: 2px solid #2e7d32; margin-bottom: 30px; padding-bottom: 20px; }
        .print-logo { height: 60px; margin-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #f4f7f6; text-align: left; padding: 12px; border: 1px solid #ddd; text-transform: uppercase; font-size: 12px; }
        td { padding: 12px; border: 1px solid #ddd; font-size: 14px; }
        .footer { margin-top: 50px; font-size: 12px; text-align: center; color: #666; }
        @media print {
            .no-print { display: none; }
            body { padding: 0; }
        }
    </style>
</head>
<body>
    <div class="no-print" style="margin-bottom: 20px; text-align: right;">
        <button onclick="window.print()" style="padding: 10px 20px; background: #2e7d32; color: white; border: none; border-radius: 5px; cursor: pointer;">🖨️ Print Daily Log</button>
        <button onclick="window.close()" style="padding: 10px 20px; background: #64748b; color: white; border: none; border-radius: 5px; cursor: pointer;">Close</button>
    </div>

    <div class="print-header">
        <img src="../assets/img/logo.png" alt="Logo" class="print-logo">
        <h1>Daily Reservation Schedule</h1>
        <p>Date: <strong><?php echo date('l, F j, Y', strtotime($today)); ?></strong></p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 15%;">Time</th>
                <th style="width: 25%;">Guest Name</th>
                <th style="width: 10%;">Guests</th>
                <th style="width: 30%;">Contact Info</th>
                <th style="width: 20%;">Arrived?</th>
            </tr>
        </thead>
        <tbody>
            <?php if (empty($daily_list)): ?>
                <tr><td colspan="5" style="text-align:center;">No active bookings for today.</td></tr>
            <?php else: ?>
                <?php foreach ($daily_list as $row): ?>
                <tr>
                    <td><strong><?php echo date('h:i A', strtotime($row['reservation_time'])); ?></strong></td>
                    <td><?php echo htmlspecialchars($row['name']); ?></td>
                    <td><?php echo $row['guests']; ?></td>
                    <td><?php echo htmlspecialchars($row['email']); ?></td>
                    <td style="color: #ccc;">[ &nbsp; ] Yes &nbsp;&nbsp; [ &nbsp; ] No</td>
                </tr>
                <?php endforeach; ?>
            <?php endif; ?>
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by The GreenLeaf Admin System on <?php echo date('Y-m-d H:i'); ?></p>
    </div>

    <script>
        window.onload = function() {
            window.print();
        };
    </script>
</body>
</html>